-- local autocmd = vim.api.nvim_create_autocmd

-- Auto resize panes when resizing nvim window
-- autocmd("VimResized", {
--   pattern = "*",
--   command = "tabdo wincmd =",
-- })
--
--require'lspconfig'.rust_analyzer.setup{}
--require'lspconfig'.clangd.setup{}
--require'lspconfig'.pylyzer.setup{}
